export const carriers = [
  {
    name: 'National Western Transport',
    mc: '234521',
    dot: '1038491',
    type: 'Asset',
    lanes: 47,
    winRate: 73,
    avgRate: '$7,820',
    onTime: 96,
    preferred: true,
    ytdLoads: 89,
    ytdSpend: '$696,180',
    contact: 'Mike Harrell — (423) 555-0182',
    email: 'dispatch@nwtransport.com',
    notes: 'Preferred for long-haul RGN and Lowboy. Strong CO/OR corridor performance.',
    equipment: ['RGN', 'Lowboy', 'Flatbed'],
    monthlyHistory: [
      { month: 'Jan', loads: 18, spend: '$140,760', onTime: 95 },
      { month: 'Feb', loads: 21, spend: '$164,220', onTime: 97 },
      { month: 'Mar', loads: 26, spend: '$203,320', onTime: 96 },
      { month: 'Apr', loads: 24, spend: '$187,680', onTime: 96 },
    ],
    topLanes: ['CHT → Denver, CO', 'CHT → Portland, OR', 'CHT → Minneapolis, MN'],
  },
  {
    name: 'Landstar System',
    mc: '191956',
    dot: '924920',
    type: 'Broker',
    lanes: 83,
    winRate: 61,
    avgRate: '$6,940',
    onTime: 94,
    preferred: true,
    ytdLoads: 124,
    ytdSpend: '$860,560',
    contact: 'Sarah Connell — (904) 555-0147',
    email: 'landstar.ops@landstar.com',
    notes: 'Largest network coverage. Broker model — agent-based. Good for spot coverage.',
    equipment: ['RGN', 'Lowboy', 'Flatbed', 'Step-Deck'],
    monthlyHistory: [
      { month: 'Jan', loads: 26, spend: '$180,440', onTime: 93 },
      { month: 'Feb', loads: 29, spend: '$201,260', onTime: 94 },
      { month: 'Mar', loads: 37, spend: '$256,780', onTime: 95 },
      { month: 'Apr', loads: 32, spend: '$222,080', onTime: 94 },
    ],
    topLanes: ['CHT → Chicago, IL', 'CHT → Kansas City, MO', 'CHT → Phoenix, AZ'],
  },
  {
    name: 'Heavy Haul America',
    mc: '487201',
    dot: '2187643',
    type: 'Asset',
    lanes: 22,
    winRate: 81,
    avgRate: '$9,340',
    onTime: 93,
    preferred: true,
    ytdLoads: 41,
    ytdSpend: '$382,940',
    contact: 'Dave Stout — (615) 555-0264',
    email: 'dispatch@heavyhaulamerica.com',
    notes: 'Specialty super-heavy haul. High win rate. Best for 100k+ lb moves.',
    equipment: ['RGN', 'Lowboy'],
    monthlyHistory: [
      { month: 'Jan', loads: 8, spend: '$74,720', onTime: 92 },
      { month: 'Feb', loads: 9, spend: '$84,060', onTime: 94 },
      { month: 'Mar', loads: 13, spend: '$121,420', onTime: 93 },
      { month: 'Apr', loads: 11, spend: '$102,740', onTime: 93 },
    ],
    topLanes: ['CHT → Minneapolis, MN', 'CHT → Los Angeles, CA', 'CHT → Houston, TX'],
  },
  {
    name: 'Anderson Trucking Service',
    mc: '318291',
    dot: '1572834',
    type: 'Asset',
    lanes: 35,
    winRate: 69,
    avgRate: '$8,150',
    onTime: 95,
    preferred: false,
    ytdLoads: 67,
    ytdSpend: '$546,050',
    contact: 'Jim Kowalski — (320) 555-0319',
    email: 'ats.ops@andersontruck.com',
    notes: 'Strong TX and Midwest lanes. Reliable on-time. Consider for preferred status.',
    equipment: ['RGN', 'Lowboy', 'Flatbed'],
    monthlyHistory: [
      { month: 'Jan', loads: 14, spend: '$113,960', onTime: 95 },
      { month: 'Feb', loads: 16, spend: '$130,400', onTime: 96 },
      { month: 'Mar', loads: 20, spend: '$163,000', onTime: 95 },
      { month: 'Apr', loads: 17, spend: '$138,550', onTime: 94 },
    ],
    topLanes: ['CHT → Dallas, TX', 'CHT → Houston, TX', 'CHT → Kansas City, MO'],
  },
  {
    name: 'ArcBest / ABF Freight',
    mc: '145421',
    dot: '615079',
    type: 'Asset',
    lanes: 29,
    winRate: 58,
    avgRate: '$4,200',
    onTime: 97,
    preferred: false,
    ytdLoads: 52,
    ytdSpend: '$218,400',
    contact: 'Tara Willis — (479) 555-0188',
    email: 'arcbest.ops@arcbest.com',
    notes: 'Best on-time performance for flatbed/step-deck. Lower win rate but very reliable.',
    equipment: ['Flatbed', 'Step-Deck'],
    monthlyHistory: [
      { month: 'Jan', loads: 11, spend: '$46,200', onTime: 97 },
      { month: 'Feb', loads: 13, spend: '$54,600', onTime: 98 },
      { month: 'Mar', loads: 15, spend: '$63,000', onTime: 97 },
      { month: 'Apr', loads: 13, spend: '$54,600', onTime: 96 },
    ],
    topLanes: ['CHT → Columbus, OH', 'CHT → Chicago, IL', 'CHT → Nashville, TN'],
  },
  {
    name: 'XPO Logistics',
    mc: '573098',
    dot: '2339271',
    type: 'Asset/Broker',
    lanes: 41,
    winRate: 52,
    avgRate: '$5,920',
    onTime: 91,
    preferred: false,
    ytdLoads: 38,
    ytdSpend: '$224,960',
    contact: 'Linda Park — (336) 555-0211',
    email: 'xpo.freight@xpo.com',
    notes: 'CA compliance strong. On-time dipping below threshold — monitor closely.',
    equipment: ['Lowboy', 'RGN', 'Flatbed'],
    monthlyHistory: [
      { month: 'Jan', loads: 8, spend: '$47,360', onTime: 92 },
      { month: 'Feb', loads: 9, spend: '$53,280', onTime: 91 },
      { month: 'Mar', loads: 12, spend: '$71,040', onTime: 91 },
      { month: 'Apr', loads: 9, spend: '$53,280', onTime: 90 },
    ],
    topLanes: ['CHT → Los Angeles, CA', 'CHT → Phoenix, AZ', 'CHT → Houston, TX'],
  },
  {
    name: 'Regional Express Freight',
    mc: '612847',
    dot: '2841927',
    type: 'Asset',
    lanes: 18,
    winRate: 77,
    avgRate: '$2,890',
    onTime: 98,
    preferred: false,
    ytdLoads: 73,
    ytdSpend: '$210,970',
    contact: 'Rob Casper — (423) 555-0344',
    email: 'dispatch@regionalexpressfreight.com',
    notes: 'Best-in-class on-time (98%). Dominates short SE regional lanes. High win rate.',
    equipment: ['Flatbed', 'Step-Deck'],
    monthlyHistory: [
      { month: 'Jan', loads: 15, spend: '$43,350', onTime: 98 },
      { month: 'Feb', loads: 18, spend: '$52,020', onTime: 99 },
      { month: 'Mar', loads: 22, spend: '$63,580', onTime: 98 },
      { month: 'Apr', loads: 18, spend: '$52,020', onTime: 98 },
    ],
    topLanes: ['CHT → Atlanta, GA', 'CHT → Nashville, TN', 'CHT → Columbus, OH'],
  },
  {
    name: 'Estes Express Lines',
    mc: '301556',
    dot: '1043167',
    type: 'Asset',
    lanes: 15,
    winRate: 45,
    avgRate: '$3,850',
    onTime: 92,
    preferred: false,
    ytdLoads: 29,
    ytdSpend: '$111,650',
    contact: 'Frank Tully — (804) 555-0166',
    email: 'estes.freight@estes-express.com',
    notes: 'Lower win rate — pricing tends to be higher. Good backup for Chicago and OH.',
    equipment: ['Flatbed', 'Step-Deck'],
    monthlyHistory: [
      { month: 'Jan', loads: 6, spend: '$23,100', onTime: 93 },
      { month: 'Feb', loads: 7, spend: '$26,950', onTime: 92 },
      { month: 'Mar', loads: 9, spend: '$34,650', onTime: 92 },
      { month: 'Apr', loads: 7, spend: '$26,950', onTime: 91 },
    ],
    topLanes: ['CHT → Chicago, IL', 'CHT → Columbus, OH', 'CHT → Nashville, TN'],
  },
]

export type Carrier = typeof carriers[number]
