export const quotes = [
  {
    id: 'CHT-0847',
    date: 'Apr 15',
    origin: 'Chattanooga, TN',
    dest: 'Denver, CO',
    equipment: 'RGN',
    lbs: '85,000',
    miles: '1,648',
    rate: '$8,400',
    baseRate: '$7,140',
    fuelSurcharge: '$924',
    accessorials: '$336',
    carrier: 'Natl Western',
    carrierMc: '234521',
    margin: '21%',
    status: 'approved',
    notes: 'Oversized load — permit required through CO. Allow 3-day lead time.',
    timeline: [
      { event: 'Quote requested', time: 'Apr 15 · 8:02 AM' },
      { event: 'Rate pulled from DAT RateView', time: 'Apr 15 · 8:03 AM' },
      { event: 'Quote approved by Steve Pack', time: 'Apr 15 · 9:47 AM' },
    ],
  },
  {
    id: 'CHT-0846',
    date: 'Apr 14',
    origin: 'Chattanooga, TN',
    dest: 'Phoenix, AZ',
    equipment: 'Lowboy',
    lbs: '92,000',
    miles: '1,979',
    rate: '$9,200',
    baseRate: '$7,820',
    fuelSurcharge: '$1,012',
    accessorials: '$368',
    carrier: 'Landstar',
    carrierMc: '191956',
    margin: '18%',
    status: 'won',
    notes: 'Heavy haul via I-40. Escort required in AZ.',
    timeline: [
      { event: 'Quote requested', time: 'Apr 14 · 7:15 AM' },
      { event: 'Rate pulled from DAT RateView', time: 'Apr 14 · 7:16 AM' },
      { event: 'Quote sent to customer', time: 'Apr 14 · 10:30 AM' },
      { event: 'Load awarded — WON', time: 'Apr 14 · 2:18 PM' },
    ],
  },
  {
    id: 'CHT-0845',
    date: 'Apr 14',
    origin: 'Chattanooga, TN',
    dest: 'Columbus, OH',
    equipment: 'Flatbed',
    lbs: '45,000',
    miles: '424',
    rate: '$3,800',
    baseRate: '$3,230',
    fuelSurcharge: '$418',
    accessorials: '$152',
    carrier: 'ArcBest',
    carrierMc: '145421',
    margin: '22%',
    status: 'pending',
    notes: 'Standard flatbed. Awaiting customer PO confirmation.',
    timeline: [
      { event: 'Quote requested', time: 'Apr 14 · 3:40 PM' },
      { event: 'Rate pulled from DAT RateView', time: 'Apr 14 · 3:41 PM' },
      { event: 'Quote sent to customer', time: 'Apr 14 · 4:05 PM' },
    ],
  },
  {
    id: 'CHT-0844',
    date: 'Apr 12',
    origin: 'Chattanooga, TN',
    dest: 'Dallas, TX',
    equipment: 'RGN',
    lbs: '78,000',
    miles: '669',
    rate: '$7,100',
    baseRate: '$6,035',
    fuelSurcharge: '$781',
    accessorials: '$284',
    carrier: 'Anderson',
    carrierMc: '318291',
    margin: '19%',
    status: 'approved',
    notes: 'Repeat lane — Anderson preferred for TX hauls.',
    timeline: [
      { event: 'Quote requested', time: 'Apr 12 · 9:00 AM' },
      { event: 'Rate pulled from DAT RateView', time: 'Apr 12 · 9:01 AM' },
      { event: 'Quote approved by Steve Pack', time: 'Apr 12 · 10:22 AM' },
    ],
  },
  {
    id: 'CHT-0843',
    date: 'Apr 11',
    origin: 'Chattanooga, TN',
    dest: 'Portland, OR',
    equipment: 'Lowboy',
    lbs: '110,000',
    miles: '2,389',
    rate: '$11,800',
    baseRate: '$10,030',
    fuelSurcharge: '$1,298',
    accessorials: '$472',
    carrier: 'Natl Western',
    carrierMc: '234521',
    margin: '15%',
    status: 'won',
    notes: 'Super-heavy haul. Multi-state permits. Route survey required.',
    timeline: [
      { event: 'Quote requested', time: 'Apr 11 · 6:45 AM' },
      { event: 'Route survey ordered', time: 'Apr 11 · 7:30 AM' },
      { event: 'Rate pulled from DAT RateView', time: 'Apr 11 · 8:00 AM' },
      { event: 'Quote sent to customer', time: 'Apr 11 · 11:15 AM' },
      { event: 'Load awarded — WON', time: 'Apr 11 · 3:52 PM' },
    ],
  },
  {
    id: 'CHT-0842',
    date: 'Apr 11',
    origin: 'Chattanooga, TN',
    dest: 'Chicago, IL',
    equipment: 'Step-Deck',
    lbs: '38,000',
    miles: '480',
    rate: '$3,200',
    baseRate: '$2,720',
    fuelSurcharge: '$352',
    accessorials: '$128',
    carrier: 'Estes',
    carrierMc: '301556',
    margin: '24%',
    status: 'pending',
    notes: 'Step-deck for tall cargo. Chicago docking restrictions apply.',
    timeline: [
      { event: 'Quote requested', time: 'Apr 11 · 1:20 PM' },
      { event: 'Rate pulled from DAT RateView', time: 'Apr 11 · 1:21 PM' },
      { event: 'Quote sent to customer', time: 'Apr 11 · 2:00 PM' },
    ],
  },
  {
    id: 'CHT-0841',
    date: 'Apr 10',
    origin: 'Chattanooga, TN',
    dest: 'Houston, TX',
    equipment: 'RGN',
    lbs: '95,000',
    miles: '834',
    rate: '$8,700',
    baseRate: '$7,395',
    fuelSurcharge: '$957',
    accessorials: '$348',
    carrier: 'Anderson',
    carrierMc: '318291',
    margin: '20%',
    status: 'approved',
    notes: 'Industrial equipment delivery to Houston port facility.',
    timeline: [
      { event: 'Quote requested', time: 'Apr 10 · 8:55 AM' },
      { event: 'Rate pulled from DAT RateView', time: 'Apr 10 · 8:56 AM' },
      { event: 'Quote approved by Steve Pack', time: 'Apr 10 · 10:15 AM' },
    ],
  },
  {
    id: 'CHT-0840',
    date: 'Apr 10',
    origin: 'Chattanooga, TN',
    dest: 'Atlanta, GA',
    equipment: 'Flatbed',
    lbs: '42,000',
    miles: '118',
    rate: '$2,100',
    baseRate: '$1,785',
    fuelSurcharge: '$231',
    accessorials: '$84',
    carrier: 'Regional Exp.',
    carrierMc: '612847',
    margin: '28%',
    status: 'won',
    notes: 'Short regional haul — Regional Express preferred.',
    timeline: [
      { event: 'Quote requested', time: 'Apr 10 · 11:00 AM' },
      { event: 'Rate pulled from DAT RateView', time: 'Apr 10 · 11:01 AM' },
      { event: 'Quote sent to customer', time: 'Apr 10 · 11:30 AM' },
      { event: 'Load awarded — WON', time: 'Apr 10 · 12:45 PM' },
    ],
  },
  {
    id: 'CHT-0839',
    date: 'Apr 9',
    origin: 'Chattanooga, TN',
    dest: 'Kansas City, MO',
    equipment: 'Step-Deck',
    lbs: '51,000',
    miles: '621',
    rate: '$4,650',
    baseRate: '$3,953',
    fuelSurcharge: '$512',
    accessorials: '$185',
    carrier: 'Landstar',
    carrierMc: '191956',
    margin: '17%',
    status: 'lost',
    notes: 'Lost to competitor. Customer went with a spot rate.',
    timeline: [
      { event: 'Quote requested', time: 'Apr 9 · 9:30 AM' },
      { event: 'Rate pulled from DAT RateView', time: 'Apr 9 · 9:31 AM' },
      { event: 'Quote sent to customer', time: 'Apr 9 · 10:00 AM' },
      { event: 'Load lost to competitor', time: 'Apr 9 · 4:15 PM' },
    ],
  },
  {
    id: 'CHT-0838',
    date: 'Apr 8',
    origin: 'Chattanooga, TN',
    dest: 'Los Angeles, CA',
    equipment: 'Lowboy',
    lbs: '88,000',
    miles: '2,180',
    rate: '$10,400',
    baseRate: '$8,840',
    fuelSurcharge: '$1,144',
    accessorials: '$416',
    carrier: 'XPO Logistics',
    carrierMc: '573098',
    margin: '16%',
    status: 'won',
    notes: 'Long-haul lowboy to LA. CA permit required.',
    timeline: [
      { event: 'Quote requested', time: 'Apr 8 · 7:00 AM' },
      { event: 'Rate pulled from DAT RateView', time: 'Apr 8 · 7:01 AM' },
      { event: 'Quote sent to customer', time: 'Apr 8 · 9:15 AM' },
      { event: 'Load awarded — WON', time: 'Apr 8 · 1:30 PM' },
    ],
  },
  {
    id: 'CHT-0837',
    date: 'Apr 7',
    origin: 'Chattanooga, TN',
    dest: 'Minneapolis, MN',
    equipment: 'RGN',
    lbs: '74,000',
    miles: '817',
    rate: '$6,900',
    baseRate: '$5,865',
    fuelSurcharge: '$759',
    accessorials: '$276',
    carrier: 'Heavy Haul USA',
    carrierMc: '487201',
    margin: '23%',
    status: 'approved',
    notes: 'MN winter routing — weight restrictions on some county roads.',
    timeline: [
      { event: 'Quote requested', time: 'Apr 7 · 8:10 AM' },
      { event: 'Rate pulled from DAT RateView', time: 'Apr 7 · 8:11 AM' },
      { event: 'Quote approved by Steve Pack', time: 'Apr 7 · 9:50 AM' },
    ],
  },
  {
    id: 'CHT-0836',
    date: 'Apr 7',
    origin: 'Chattanooga, TN',
    dest: 'Nashville, TN',
    equipment: 'Flatbed',
    lbs: '36,000',
    miles: '134',
    rate: '$1,950',
    baseRate: '$1,658',
    fuelSurcharge: '$215',
    accessorials: '$78',
    carrier: 'Regional Exp.',
    carrierMc: '612847',
    margin: '31%',
    status: 'won',
    notes: 'Short in-state haul. Quick turnaround.',
    timeline: [
      { event: 'Quote requested', time: 'Apr 7 · 2:00 PM' },
      { event: 'Rate pulled from DAT RateView', time: 'Apr 7 · 2:01 PM' },
      { event: 'Quote sent to customer', time: 'Apr 7 · 2:30 PM' },
      { event: 'Load awarded — WON', time: 'Apr 7 · 3:15 PM' },
    ],
  },
]

export type Quote = typeof quotes[number]
