export const lanes = [
  {
    origin: 'Chattanooga, TN',
    dest: 'Atlanta, GA',
    miles: '118',
    loads: 67,
    avgRate: '$1,734',
    minRate: '$1,400',
    maxRate: '$2,100',
    ratePerMile: '$14.69',
    trend: 'flat' as const,
    topCarriers: ['Regional Exp.', 'ArcBest', 'Estes'],
    equipment: ['Flatbed', 'Step-Deck'],
    monthlyHistory: [
      { month: 'Jan', loads: 14, avgRate: '$1,690', savings: '$2,100' },
      { month: 'Feb', loads: 16, avgRate: '$1,710', savings: '$2,440' },
      { month: 'Mar', loads: 19, avgRate: '$1,750', savings: '$2,870' },
      { month: 'Apr', loads: 18, avgRate: '$1,785', savings: '$2,760' },
    ],
    notes: 'High-volume short haul. Regional Express dominates. Rates stable.',
  },
  {
    origin: 'Chattanooga, TN',
    dest: 'Chicago, IL',
    miles: '480',
    loads: 52,
    avgRate: '$2,967',
    minRate: '$2,400',
    maxRate: '$3,600',
    ratePerMile: '$6.18',
    trend: 'flat' as const,
    topCarriers: ['Estes', 'ArcBest', 'Landstar'],
    equipment: ['Step-Deck', 'Flatbed'],
    monthlyHistory: [
      { month: 'Jan', loads: 11, avgRate: '$2,890', savings: '$3,450' },
      { month: 'Feb', loads: 13, avgRate: '$2,930', savings: '$3,820' },
      { month: 'Mar', loads: 15, avgRate: '$2,980', savings: '$4,560' },
      { month: 'Apr', loads: 13, avgRate: '$3,070', savings: '$3,970' },
    ],
    notes: 'Moderate volume. Watch for Chicago docking restrictions on oversized.',
  },
  {
    origin: 'Chattanooga, TN',
    dest: 'Columbus, OH',
    miles: '424',
    loads: 47,
    avgRate: '$2,841',
    minRate: '$2,200',
    maxRate: '$3,500',
    ratePerMile: '$6.70',
    trend: 'up' as const,
    topCarriers: ['ArcBest', 'Estes', 'Landstar'],
    equipment: ['Flatbed', 'Step-Deck', 'RGN'],
    monthlyHistory: [
      { month: 'Jan', loads: 9, avgRate: '$2,690', savings: '$2,800' },
      { month: 'Feb', loads: 11, avgRate: '$2,780', savings: '$3,200' },
      { month: 'Mar', loads: 14, avgRate: '$2,870', savings: '$4,100' },
      { month: 'Apr', loads: 13, avgRate: '$3,025', savings: '$3,800' },
    ],
    notes: 'Growing lane — rate trending up. Consider locking preferred rates.',
  },
  {
    origin: 'Chattanooga, TN',
    dest: 'Nashville, TN',
    miles: '134',
    loads: 44,
    avgRate: '$1,876',
    minRate: '$1,500',
    maxRate: '$2,300',
    ratePerMile: '$14.00',
    trend: 'up' as const,
    topCarriers: ['Regional Exp.', 'ArcBest'],
    equipment: ['Flatbed'],
    monthlyHistory: [
      { month: 'Jan', loads: 9, avgRate: '$1,800', savings: '$1,620' },
      { month: 'Feb', loads: 10, avgRate: '$1,840', savings: '$1,840' },
      { month: 'Mar', loads: 13, avgRate: '$1,895', savings: '$2,470' },
      { month: 'Apr', loads: 12, avgRate: '$1,950', savings: '$2,340' },
    ],
    notes: 'High $/mile lane. Regional Express preferred for short TN hauls.',
  },
  {
    origin: 'Chattanooga, TN',
    dest: 'Dallas, TX',
    miles: '669',
    loads: 38,
    avgRate: '$4,192',
    minRate: '$3,400',
    maxRate: '$5,200',
    ratePerMile: '$6.26',
    trend: 'flat' as const,
    topCarriers: ['Anderson', 'Landstar', 'XPO Logistics'],
    equipment: ['RGN', 'Lowboy'],
    monthlyHistory: [
      { month: 'Jan', loads: 8, avgRate: '$4,050', savings: '$5,200' },
      { month: 'Feb', loads: 9, avgRate: '$4,120', savings: '$5,750' },
      { month: 'Mar', loads: 11, avgRate: '$4,230', savings: '$7,040' },
      { month: 'Apr', loads: 10, avgRate: '$4,370', savings: '$6,380' },
    ],
    notes: 'Anderson Trucking preferred on RGN. Watch TX permit requirements.',
  },
  {
    origin: 'Chattanooga, TN',
    dest: 'Houston, TX',
    miles: '834',
    loads: 29,
    avgRate: '$5,421',
    minRate: '$4,400',
    maxRate: '$6,600',
    ratePerMile: '$6.50',
    trend: 'up' as const,
    topCarriers: ['Anderson', 'Heavy Haul America', 'XPO Logistics'],
    equipment: ['RGN', 'Lowboy'],
    monthlyHistory: [
      { month: 'Jan', loads: 5, avgRate: '$5,200', savings: '$3,800' },
      { month: 'Feb', loads: 7, avgRate: '$5,310', savings: '$4,920' },
      { month: 'Mar', loads: 9, avgRate: '$5,480', savings: '$6,340' },
      { month: 'Apr', loads: 8, avgRate: '$5,695', savings: '$5,760' },
    ],
    notes: 'Industrial route to Houston port. Rates climbing — 3 months trend.',
  },
  {
    origin: 'Chattanooga, TN',
    dest: 'Denver, CO',
    miles: '1,648',
    loads: 23,
    avgRate: '$5,847',
    minRate: '$4,800',
    maxRate: '$7,200',
    ratePerMile: '$3.55',
    trend: 'up' as const,
    topCarriers: ['Natl Western', 'Landstar'],
    equipment: ['RGN', 'Lowboy'],
    monthlyHistory: [
      { month: 'Jan', loads: 4, avgRate: '$5,590', savings: '$3,400' },
      { month: 'Feb', loads: 5, avgRate: '$5,710', savings: '$4,100' },
      { month: 'Mar', loads: 7, avgRate: '$5,890', savings: '$6,230' },
      { month: 'Apr', loads: 7, avgRate: '$6,200', savings: '$6,580' },
    ],
    notes: 'Natl Western preferred for CO. CO oversize permits — allow 3 days.',
  },
  {
    origin: 'Chattanooga, TN',
    dest: 'Kansas City, MO',
    miles: '621',
    loads: 21,
    avgRate: '$4,083',
    minRate: '$3,200',
    maxRate: '$5,100',
    ratePerMile: '$6.57',
    trend: 'down' as const,
    topCarriers: ['Landstar', 'Anderson'],
    equipment: ['Step-Deck', 'RGN'],
    monthlyHistory: [
      { month: 'Jan', loads: 6, avgRate: '$4,310', savings: '$4,120' },
      { month: 'Feb', loads: 6, avgRate: '$4,190', savings: '$3,980' },
      { month: 'Mar', loads: 5, avgRate: '$4,040', savings: '$3,420' },
      { month: 'Apr', loads: 4, avgRate: '$3,790', savings: '$2,870' },
    ],
    notes: 'Rate declining and volume dropping. Monitor for market softening.',
  },
  {
    origin: 'Chattanooga, TN',
    dest: 'Minneapolis, MN',
    miles: '817',
    loads: 19,
    avgRate: '$5,172',
    minRate: '$4,100',
    maxRate: '$6,400',
    ratePerMile: '$6.33',
    trend: 'up' as const,
    topCarriers: ['Heavy Haul America', 'Landstar'],
    equipment: ['RGN', 'Lowboy'],
    monthlyHistory: [
      { month: 'Jan', loads: 4, avgRate: '$4,890', savings: '$3,200' },
      { month: 'Feb', loads: 4, avgRate: '$5,050', savings: '$3,400' },
      { month: 'Mar', loads: 6, avgRate: '$5,220', savings: '$4,800' },
      { month: 'Apr', loads: 5, avgRate: '$5,530', savings: '$4,100' },
    ],
    notes: 'MN winter weight restrictions may apply Jan–Mar on county routes.',
  },
  {
    origin: 'Chattanooga, TN',
    dest: 'Phoenix, AZ',
    miles: '1,979',
    loads: 18,
    avgRate: '$7,213',
    minRate: '$5,800',
    maxRate: '$9,100',
    ratePerMile: '$3.65',
    trend: 'down' as const,
    topCarriers: ['Landstar', 'XPO Logistics'],
    equipment: ['Lowboy', 'RGN'],
    monthlyHistory: [
      { month: 'Jan', loads: 5, avgRate: '$7,540', savings: '$4,900' },
      { month: 'Feb', loads: 5, avgRate: '$7,310', savings: '$4,600' },
      { month: 'Mar', loads: 5, avgRate: '$7,120', savings: '$4,300' },
      { month: 'Apr', loads: 3, avgRate: '$6,880', savings: '$2,560' },
    ],
    notes: 'Rate softening — spot market competition increasing in AZ corridor.',
  },
  {
    origin: 'Chattanooga, TN',
    dest: 'Los Angeles, CA',
    miles: '2,180',
    loads: 15,
    avgRate: '$8,941',
    minRate: '$7,200',
    maxRate: '$11,200',
    ratePerMile: '$4.10',
    trend: 'up' as const,
    topCarriers: ['XPO Logistics', 'Landstar', 'Heavy Haul America'],
    equipment: ['Lowboy', 'RGN'],
    monthlyHistory: [
      { month: 'Jan', loads: 3, avgRate: '$8,490', savings: '$3,800' },
      { month: 'Feb', loads: 3, avgRate: '$8,720', savings: '$3,950' },
      { month: 'Mar', loads: 5, avgRate: '$9,020', savings: '$6,740' },
      { month: 'Apr', loads: 4, avgRate: '$9,534', savings: '$5,420' },
    ],
    notes: 'CA permits required. XPO preferred for CA compliance.',
  },
  {
    origin: 'Chattanooga, TN',
    dest: 'Portland, OR',
    miles: '2,389',
    loads: 12,
    avgRate: '$9,876',
    minRate: '$8,100',
    maxRate: '$12,400',
    ratePerMile: '$4.13',
    trend: 'up' as const,
    topCarriers: ['Natl Western', 'Heavy Haul America'],
    equipment: ['Lowboy', 'RGN'],
    monthlyHistory: [
      { month: 'Jan', loads: 2, avgRate: '$9,340', savings: '$2,700' },
      { month: 'Feb', loads: 3, avgRate: '$9,620', savings: '$4,100' },
      { month: 'Mar', loads: 4, avgRate: '$9,980', savings: '$5,480' },
      { month: 'Apr', loads: 3, avgRate: '$10,564', savings: '$4,100' },
    ],
    notes: 'Super-heavy corridor. Multi-state permits. Route survey often needed.',
  },
]

export type Lane = typeof lanes[number]
